kind: Deployment
apiVersion: apps/v1
metadata:
  name: openshift-acme
  labels:
    app: openshift-acme
  annotations:
spec:
  selector:
    matchLabels:
      app: openshift-acme
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: openshift-acme
    spec:
      serviceAccountName: openshift-acme
      containers:
      - name: openshift-acme
        image: "quay.io/tnozicka/openshift-acme:controller"
        args:
        - "--loglevel=2"
        imagePullPolicy: Always
        env:
        - name: OPENSHIFT_ACME_EXPOSER_IMAGE
          value: "quay.io/tnozicka/openshift-acme:exposer"
