kind: Deployment
apiVersion: apps/v1
metadata:
  name: openshift-acme
  labels:
    app: openshift-acme
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"openshift-acme:controller"},"fieldPath":"spec.template.spec.containers[?(@.name==\"openshift-acme\")].image"},{"from":{"kind":"ImageStreamTag","name":"openshift-acme:exposer"},"fieldPath":"spec.template.spec.env[?(@.name==\"OPENSHIFT_ACME_EXPOSER_IMAGE\")].value"}]'
spec:
  selector:
    matchLabels:
      app: openshift-acme
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: openshift-acme
    spec:
      serviceAccountName: openshift-acme
      containers:
      - name: openshift-acme
        image: " "
        args:
        - "--loglevel=2"
        - ""
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: OPENSHIFT_ACME_EXPOSER_IMAGE
          value: "4"
